name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.85.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all-features
      - name: Formatting
        run: cargo +nightly fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - uses: actions/checkout@v4
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo nextest run --all-features
